#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	fgrep='fgrep --color=auto' \
	egrep='egrep --color=auto' \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"
	dir='dir --color=auto' \
	vdir='vdir --color=auto' \

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner" \
	yt="youtube-dl --add-metadata -ic" \
	yta="youtube-dl -f bestaudio/best --add-metadata -xic" \
	ping="ping -c 5" \
	fastping="ping -c 100 -s.2" \
	gh="history|grep" \
	count="find . -type f | wc -l" \
	cpv="rsync -ah --info=progress2" \
	ll='ls -alhF' \
	la='ls -A' \
	l='ls -CF' \
	lt='ls --human-readable --size -1 -S --classify' \
	mnt="mount | awk -F' ' '{ printf \"%s\t%s\n\",\$1,\$3; }' | column -t | egrep ^/dev/ | sort" \
	alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"' \

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="sudo shutdown -h now" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="doas pacman" \
	xi="doas xbps-install" \
	xr="doas xbps-remove -R" \
	xq="xbps-query" \
	z="zathura" \
	h="history" \
	myip="curl ipinfo.io/ip" \
	cl="clear" \
	sdn="doas shutdown -h now" \
	nv="nvim" \
	snv="sudo nvim" \
	reboot="doas reboot"\
	updateWebsite="rsync -vrP --delete-after ~/org/html/* root@keithbutler.xyz:/var/www/keithbutler/" \
	unrealEngine="/home/keith/Documents/UnrealEngine/Engine/Binaries/Linux/UE4Editor"

alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/zshnameddirrc" \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \
	tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf" \
